import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/Header";
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
import GoTop from "@/components/GoTop/Gotop";
import Footer from "@/components/footer/Footer";
import CombinedHeader from "@/components/header/CombineHeader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Evolzer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
        <CombinedHeader />
        <GoTop/>
        <div className="absolute inset-0 z-0">{children}
        <Footer/>
        </div> {/* This positions the children behind the header */}

       
      </body>
    </html>
  );
}
